import {useEffect,useState} from 'react';
import {CartesianGrid,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import {ActionPerformance,type ActionReplayPayload} from './action-performance.js';
type Report=ReturnType<typeof import('../server/pnl.js').simulatePortfolio>;
type ReplayRow={symbol:string;marketAsOf:string;action:'long'|'short'|'flat';previousAction:'long'|'short'|'flat'};
const side={long:'롱',short:'숏',flat:'무포지션'};
type Payload={task?:undefined;history?:ReplayRow[];status:'pending'|'ready';model?:string;revision?:string;generatedAt?:string;source?:string;report?:Report};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
export function Performance(){
 const [raw,setData]=useState<Payload|ActionReplayPayload|null>(null),[error,setError]=useState(false),[retry,setRetry]=useState(0);
 useEffect(()=>{const ac=new AbortController();setError(false);fetch('/api/performance',{signal:ac.signal}).then(r=>{if(!r.ok)throw Error();return r.json();}).then(setData).catch(e=>{if(e.name!=='AbortError')setError(true);});return()=>ac.abort();},[retry]);
 const [historySymbol,setHistorySymbol]=useState('전체'),[historyPage,setHistoryPage]=useState(0);
 const data=raw?.task==='ACTION_V1'?null:raw;
 const history=(data?.history??[]).filter(row=>historySymbol==='전체'||row.symbol===historySymbol);
 const report=data?.report,last=report?.curve.at(-1),first=report?.curve[0];
 const mdd=report?.maxDrawdownPct??0;
 const cadence=report?.assumptions.intervalMinutes??240;
 const capital=report?.initialCapital??10000, count=report?.perSymbol.length??10, fee=(report?.assumptions.feeBps??5)/100,slip=(report?.assumptions.slippageBps??2)/100;
 if(raw?.task==='ACTION_V1')return <ActionPerformance data={raw}/>;
 return <section className="card performance" aria-label="가상 운용 PnL">
  <div className="performance-heading"><div><span className="performance-eyebrow">MODEL REPLAY</span><h2>jev뇨띠 PnL</h2><p>과거 판단을 이어서 운용했다면{data?.source?.includes('USDT')?' · 금액 단위 USDT ($ 표기)':''}</p></div><span className="performance-badge">{data?.status==='ready'?'사후 재현':'백필 대기'}</span></div>
  <div className="performance-metrics"><div><span>총 손익</span><strong>{last?money(last.pnl):'—'}</strong></div><div><span>누적 수익률</span><strong>{last?`${last.returnPct.toFixed(2)}%`:'—'}</strong></div><div><span>최대 낙폭 · {cadence/60}시간 종가</span><strong>{last?`${mdd.toFixed(2)}%`:'—'}</strong></div><div><span>매수 후 보유 수익률</span><strong>{last?`${report!.buyHoldReturnPct.toFixed(2)}%`:'—'}</strong></div></div>
  {error?<div className="performance-empty" role="alert"><p>성과 데이터를 불러오지 못했어요.</p><button className="secondary-button" onClick={()=>setRetry(v=>v+1)}>다시 불러오기</button></div>:!data?<div className="performance-empty" role="status">성과 데이터 확인 중</div>:!last?<div className="performance-empty"><span className="performance-empty-symbol">↗</span><h3>첫 운용 기록을 기다리고 있어요</h3><p>10종목 · 4시간마다 판단 · 최근 구간 우선<br/>최근 5년을 목표로, $10 예산 안에서 완료한 구간을 표시합니다.</p><small>완료된 운용 기록이 아직 없습니다. 수익률 0%를 뜻하지 않습니다.</small></div>:<><div className="performance-chart" role="img" aria-label="모델 가상 운용 및 매수 후 보유 자산 곡선"><ResponsiveContainer width="100%" height="100%"><LineChart data={report!.curve}><CartesianGrid vertical={false} stroke="#e8e2d8"/><XAxis dataKey="time" tickFormatter={v=>String(v).slice(0,10)} minTickGap={65}/><YAxis tickFormatter={v=>`$${Number(v).toLocaleString()}`} width={80}/><Tooltip formatter={v=>money(Number(v))}/><Line name="jev뇨띠" dataKey="equity" stroke="#a95546" dot={false} isAnimationActive={false}/><Line name="매수 후 보유" dataKey="buyHoldEquity" stroke="#99958c" strokeDasharray="4 4" dot={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div><p className="performance-range">실선 jev뇨띠 · 점선 매수 후 보유 · UTC · {first?.time.slice(0,16).replace('T',' ')} — {last.time.slice(0,16).replace('T',' ')} · <span title={data.source}>{data.source?.startsWith('Binance')?'Binance Spot · USDT':data.source}</span> · <span title={data.revision}>jev-nyotti / {data.revision?.split('@').at(-1)?.slice(0,7)}</span></p><div className="performance-symbols">{report!.perSymbol.map(row=><div key={row.symbol}><span>{row.symbol.replace(/USDT?$/,'')}</span><strong>{money(row.pnl)}</strong><span>{row.returnPct.toFixed(2)}%</span></div>)}</div></>}
  {report&&report.perSymbol.every(row=>row.fills===0)&&<p className="performance-range">이 구간에서는 모델이 무포지션을 유지했습니다. 거래가 없어 모델 운용 손익과 거래 비용이 0입니다.</p>}
  {!!data?.history?.length&&<details className="performance-rules"><summary>과거 판단 기록 · {data.history.length.toLocaleString()}건</summary><div className="replay-history-controls"><label>종목 <select value={historySymbol} onChange={e=>{setHistorySymbol(e.target.value);setHistoryPage(0);}}><option>전체</option>{report!.perSymbol.map(row=><option key={row.symbol}>{row.symbol}</option>)}</select></label><span>최신순 · UTC · 직전 포지션 → 판단</span></div><div className="replay-history-rows">{history.slice(historyPage*20,(historyPage+1)*20).map(row=><div key={row.symbol+row.marketAsOf}><time>{row.marketAsOf.slice(0,16).replace('T',' ')}</time><span>{row.symbol.replace(/USDT?$/,'')}</span><span>{side[row.previousAction]} → <strong>{side[row.action]}</strong></span></div>)}</div><div className="replay-history-controls"><button className="secondary-button" disabled={!historyPage} onClick={()=>setHistoryPage(v=>v-1)}>이전</button><span>{historyPage+1} / {Math.ceil(history.length/20)}</span><button className="secondary-button" disabled={(historyPage+1)*20>=history.length} onClick={()=>setHistoryPage(v=>v+1)}>다음</button></div></details>}
  <details className="performance-rules"><summary>가상 운용 계산 기준</summary><p>{money(capital)} 시작 · {count}종목 균등 배분 · 진입 시 1배 · 첫 포지션 없음. 이후 {cadence/60}시간마다 직전 판단을 전달하며 롱·숏·무포지션을 이어갑니다.</p><p>판단에 사용한 캔들이 닫힌 뒤 다음 봉 시가에 체결합니다. 방향이 같으면 수량을 유지하고, 방향이 바뀌면 청산 후 진입합니다. 거래금액마다 수수료 {fee}% + 슬리피지 {slip}%를 가정합니다.</p><p>입력은 닫힌 1시간 봉입니다. 모델은 다음 1시간의 포지션을 예측하며, 이 전략은 그 판단을 {cadence/60}시간 유지합니다. 4시간 수익률을 예측하도록 재학습한 모델은 아닙니다.</p><p>펀딩비·차입비·마지막 미청산 포지션의 청산 비용은 미반영입니다. 종가 기준 평가손익을 포함합니다. 실제 운용 수익이 아니며, 학습 기간과 겹치는 데이터는 독립적인 성능 검증이 아닙니다.</p></details>
 </section>;
}
